name: example
description: Example application for riverpod_dev_logger.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  riverpod: '>=2.0.0 <4.0.0'
  riverpod_dev_logger:
    path: ../

dev_dependencies:
  lints: ^3.0.0
